### ISSUE TITLE
Documentation suggestion -- use HOST mode for container

### ISSUE THREAD

**Issue by chsull** [brbeaird/SmartThings-MyQ-Edge#1]
Hi -- first -- thanks for creating this!

Just a documentation suggestion. I added this as a container on my QNAP server and found I had to enable "Host" Network Mode in the container advanced settings -- default is "NAT" mode. I assume that the port was not being exported when running in NAT mode.

**Comment by brbeaird** [comment]
Yep, good catch. I'm actively trying to figure out a way to get this to work in bridge/NAT mode, but I'm not there yet. I went ahead and added a note to the readme.

**Comment by mikeyhenein** [comment]
For anyone using Portainer, add this to your Stack.
network_mode: host
