### ISSUE TITLE
Bad Auth error

### ISSUE THREAD

**Issue by BlueQue** [brbeaird/SmartThings-MyQ-Edge#11]
I set up everything last week and had everything working without issue.  I am running the win exe version, and it seemed to be just fine.  However today I noticed that I was showing an invalid credentials error when trying to control the MyQ garage doors.  After looking at the smarthings CLI log info I was getting the following error:

INFO MyQ Connector  Bad auth.

This is odd as I had not changed anything on my side and the MyQ app was working with the same credentials that were entered into the config for the the MyQ Connector.  I tried a number of things in the config, setting it to the wrong password and then changing it back and such, but nothing seemed to work.  Last thing I tried was to switch the driver to a different driver (I used the beta driver in this case), and then switched back to the original driver.  I did not change the password or settings when doing this switch.  Everything started to work at that point again.  Seems like there might be a bug in the driver that gets stuck and fails auth and has no way to recover.  Also error message was a bit confusing as I originally thought that the auth error was on the server instance and not in the driver connection.

Seems like I was able to work around the issue, so this is more just an FYI, and ask that additional hardening be looked at for the driver authentication process.

Thanks overall for all the work you have done to make this work, really appreciate it!

**Comment by brbeaird** [comment]
I agree - I think something is causing things to stall. A few people have reported it, but so far, I have not been able to reproduce it. The logic should already handle it and gracefully pick things back up. Hopefully I can track it down.

**Comment by brbeaird** [comment]
I believe I found the issue and pushed an update to the Edge driver to fix this https://github.com/brbeaird/SmartThings-MyQ-Edge/commit/a0770ad2e81228b2d666afac8cc561288189851c
