### ISSUE TITLE
Awaiting credentials...

### ISSUE THREAD

**Issue by briandmiller** [brbeaird/SmartThings-MyQ-Edge#14]
I too am stuck on Awaiting credentials after entering my username and password to the MyQ-Controller 

Please advise

**Comment by AdventureJon** [comment]
briandmiller, I had this issue when I set up my MyQ account using Google authentication.  I solved this by converting MyQ account authentication from Google to native MyQ by going to https://www.myq.com/login and selecting "Forgot Password" and going through the steps.  This allowed me to set a specific native password for my MyQ account and solved the credentials issue.  3rd party authentication isn't currently supported

**Comment by briandmiller** [comment]
Thanks for the response but I started out with native MyQ email login.

**Comment by brbeaird** [comment]
I believe I found the issue and pushed an update to the Edge driver to fix this https://github.com/brbeaird/SmartThings-MyQ-Edge/commit/a0770ad2e81228b2d666afac8cc561288189851c

**Comment by tmsteinhardt** [comment]
I believe I'm having a similar issue.  Went through all the steps to install and setup MyQ on Docker on a RaspPi and entered my credentials in the driver in Smartthings but it just sits at the MyQStatus of Searching for bridge server with MyQserveraddress Pending.  I know docker is running but can't confirm that the myq package is running properly.  If I try re-running the container I just get a message that states that the container is already in use by another container.

**Comment by donbay** [comment]
I just set this up using the executable and it worked great 1 time, now it's stuck awaiting credentials. I've reentered my credentials but it's still stuck.

**Comment by brbeaird** [comment]
This usually means your Docker container is not exposed in a way that the SmartThings hub can connect to it. That could mean firewall settings or could mean you need to specifically enter IP and port in the MyQ-Controller device in SmartThings.
