### ISSUE TITLE
MyQ Bridge Offline

### ISSUE THREAD

**Issue by AdventureJon** [brbeaird/SmartThings-MyQ-Edge#15]
I'm running V3 hub and the MyQ-Controller on Windows server using the Windows executable on a specific port.  The MyQ-Controller is running and I can add the controller to my SmartThings however as soon as I add my credentials, the hub gives me a status of "Error:MyQ Bridge Offline:my.ip.add.res:myport.   I've opened my port and UDP 1900 on the firewall for the server and even forwarded the same ports on my router but no joy.   
The log, repeats the following sequence:
2023-01-03T03:54:09.539380618+00:00 ERROR MyQ Connector  Request timed out.http://192.168.10.75:45678/devices
2023-01-03T03:54:09.566470285+00:00 ERROR MyQ Connector  Refresh Failed.
2023-01-03T03:54:09.571607285+00:00 DEBUG MyQ Connector  MyQ-Controller device thread event handled

Not sure where to look to solve this and looking for some guidance.

**Comment by AdventureJon** [comment]
Is there any additional information I can provide to help figure out this issue?

**Comment by AdventureJon** [comment]
Does anyone else have this issue after entering the MyQ Credentials in the SmartThings app?

**Comment by AdventureJon** [comment]
Ok, well I guess this project doesn't work.   I have not been able to get the connector to communicate with MyQ.

**Comment by brbeaird** [comment]
I pushed a recent update with a fix that could potentially help your issue if you want to try again. Sorry it hasn't been working out for you. I can tell you it's still working great for me and for a pretty large number of others.

**Comment by AdventureJon** [comment]
Hi Brian, much appreciate the attempt.  I deleted the device on SmartThings, removed the driver, stopped the connector, reinstalled the driver, downloaded and ran the new MyQBridgeServer-win-x64.exe, then readded the device in SmartThings and entered my credentials in the device settings.  The result is the same.  In Smartthings, "Error:MyQ Bridge Offline:http://ip:port" and the connector log repeats the same three messages as above every few seconds.  Is there anywhere I can look on my side that can point me in the right direction?  While I'm not a programmer, I am pretty technically savvy.

**Comment by AdventureJon** [comment]
Additional troubleshooting:  If I turn my firewall off (machine running the bridge server) and remove the Server IP and Server Port setting from SmartThings, the Bridge server detects SSDP Broadcast and indicates it is posting back to my SmartThings hub on port 54894.  My SmartThings hub however appears to be timing out on its search for the bridge server.  Logs are attached from both SmartThings and Bridge Server.
![MyQBridgeServer Log](https://user-images.githubusercontent.com/46487265/211844897-f136177f-73ee-41d6-92e3-1f0586f4f983.jpg)
![Smartthings Hub Log](https://user-images.githubusercontent.com/46487265/211844898-3e83a4d2-01e5-4a6f-99c2-2065f45271b8.jpg)

**Comment by brbeaird** [comment]
This is good info. So this means:

1. The hub is broadcasting the SSDP request
2. The bridge server is seeing the broadcast
3. The bridge is successfully posting a payload back to the hub
4. The hub is not able to make an HTTP request to the bridge server

The search itself appears to actually be successful. The problem is not being able to connect over http after that point. My guess is something is blocking incoming http requests to the bridge server running the executable. I assume from those logs that the IP of your bridge server is 192.168.10.75. What happens if you try to hit http://192.168.10.75:8090/status from a browser of another machine (or maybe your phone) on your LAN?

**Comment by AdventureJon** [comment]
I get a message that states the site cannot be reached - 192.168.10.75 took too long to respond.

**Comment by brbeaird** [comment]
Hmm yeah something isn't quite right. Can you that address from the machine locally? If you can figure out why traffic can't get in on 8090, I think this will start working.

**Comment by AdventureJon** [comment]
I tried it locally on the machine and also disabled IIS but the result was the same.  I am going to try running the bridge server on a different machine and see if it is machine specific.

**Comment by AdventureJon** [comment]
Ok, here is the update - I ran the MyQBridgeServer on a different machine.  It immediately popped up with a firewall setup.  I accepted the firewall setup (It opened all TCP and UDP ports for the program) and the server started on port 63350.  The server connected to MyQ (flag of success).  I then set the environment variable to a specific port (same port 63350) and restarted the MyQBridgeServer and it connected again.  I duplicated the two firewall entries on my original server (Windows Server 2016 machine) and it connected.  I then restricted the inbound open ports in the firewall entries to only UDP port 1900 and TCP port 63350 - the server started however attempted to post back to the hub on port 54895.  I opened inbound TCP and UDP port 54895 and no joy.  I opened ALL TCP ports and the server connected.  I attempted to operate the door and got an error.  I opened ALL inbound UDP ports and door operated as intended.   Moral of the story, the communications between SmartThings Hub and the MyQBridgeServer and MyQBridgeServer and MyQ require all inbound UDP and TCP ports to be open for the MyQBridgeServer program.  While not ideal from a security perspective, it works.   
@Brian - many thanks for working this through with me.  If you have the opportunity, it would be good to better understand the ports that are needed so we can narrow the ports for the inbound firewall for a more secure system.  I'm happy to help if I can.  
Please see the summary of Firewall entries that I entered to make this work. (Windows 10 recommends this automatically, other versions like Server 2016 need to be manually entered)
![Firewall](https://user-images.githubusercontent.com/46487265/212134126-ab1023b5-6a6a-4547-a5c1-c9bbf697c341.jpg)

**Comment by brbeaird** [comment]
Ok, so one thing you need to know is the hub's HTTP receiving port is randomized, so anytime the Edge driver or the hub itself restarts, the port number will change. However, that's really only relevant during IP auto-discovery.

The Bridge server's port will also be randomized unless you set it in an environment variable.

Other than that, both will need UDP 1900 to handle SSDP broadcast, again only during IP auto-discovery.

When the bridge server sends commands to doors, that is simply outbound HTTP traffic on 443 out the Internet. As for how the door device actually receives that command from the MyQ cloud, I am not sure.

All that said, this should be possible to run without all ports needing to be open. I am currently running the bridge server within a docker container where ONLY ports 8090 TCP and 1900 UDP are open. I can't say for sure what ports are needed for the hub and the MyQ gateway/doors as I have never tried to lock those down separately.
