### ISSUE TITLE
bad credentials

### ISSUE THREAD

**Issue by OneOfOneGH** [brbeaird/SmartThings-MyQ-Edge#16]
after initially not being able to find the server [its on an old laptop] I figured out that it needs ethernet so I connected that way and voila it found the server using automatic settings. now it says bad credentials even though I used my myQ login for the credentials. when the last issue came up [ a year ago?] and the setup needed a weird generated key, its creation using the instructions worked. is that now the issue for the bad credentials or is there another way to enter email and password for this to work which is a long-winded way of saying is the login for the controller different than the myQ login? thanks in advance for your work.

**Comment by OneOfOneGH** [comment]
turns out that my login is from 2018 so and the mychamberlain site doesnt even exist anymore. so can anyone tell me that I should just change the login at the new myQ site and that should work?

**Comment by brbeaird** [comment]
Maybe? I really can't say for sure, so I'd say give it a shot. The login flow should actually be the same as the latest iteration of the SmartApp that was working, but I don't know why you would be having issues now.

**Comment by OneOfOneGH** [comment]
for whatever reason it decided to connect? is it safe to assume that the key generator portion of the old app is no longer necessary? and thank you for your work

**Comment by brbeaird** [comment]
Yes, the old auth piece is no longer needed. The new flow simply takes username/password set at the MyQ-Controller device in SmartThings.
