### ISSUE TITLE
Doesn't auth against SSO to Google?

### ISSUE THREAD

**Issue by djbooya** [brbeaird/SmartThings-MyQ-Edge#17]
I authenticate my myq app via google auth.  Is this supported or do I need to re-configure the access to use simple username/password?

**Comment by djbooya** [comment]
A workaround I'm attempting right now is:
1) create new myq account with email / password
2) I'm going to invite that to my "main" account which is google oauthd

Hopefully that "guest" account will have access for the integration to work.  It looks like auth succeeded:
1/14/2023, 10:06:00 PM | Refresh failed
1/14/2023, 8:08:43 PM | HTTP server listening on port 8090
1/14/2023, 8:08:43 PM | SSDP server up and listening for broadcasts: urn:SmartThingsCommunity:device:MyQController
1/14/2023, 9:23:02 PM | HTTP server listening on port 8090
1/14/2023, 9:23:02 PM | SSDP server up and listening for broadcasts: urn:SmartThingsCommunity:device:MyQController
1/14/2023, 9:26:52 PM | Got new username/password from hub. Initializing connection.
1/14/2023, 10:13:28 PM | Got new username/password from hub. Initializing connection.
myQ API: Successfully connected to the myQ API.

**Comment by brbeaird** [comment]
SSO is not supported - your workaround is clever, though. I think that should work!

**Comment by djbooya** [comment]
It did work...I created another account @myq with

username+myq@domain.com (and then granted that access to my SSOd account.  Maybe something to put in your docs as the workaround.
