### ISSUE TITLE
ARM 32-bit version?

### ISSUE THREAD

**Issue by robross0606** [brbeaird/SmartThings-MyQ-Edge#18]
Any chance of getting a compiled Arm 32-bit version of this?

**Comment by robross0606** [comment]
Wait, is this just a Node.js service?  If so, what are the various "executables" for?

**Comment by brbeaird** [comment]
You are right - this is just a node server, so if you know how to deal with that, you can just run it from the source directly. Or you can run it in a docker container.

The executables are for people who have no experience with NodeJs or Docker - just makes it a bit simpler as a single file that can be run in that case.

**Comment by brbeaird** [comment]
Also, just to clarify the original question - no, I don't think I have an existing 32-bit I can use to compile an executable.
