### ISSUE TITLE
Cannot get Docker to work on Smartthings

### ISSUE THREAD

**Issue by stephengpowell** [brbeaird/SmartThings-MyQ-Edge#19]
Cannot get Docker to work on Samrtthings

**Comment by stephengpowell** [comment]
I have Docker installed but when I get to the point to Pull Image of create container it will not work

**Comment by brbeaird** [comment]
Sorry, I can't help a ton with Docker installs. A lot of people in the SmartThings community thread recommend using Portainer, which makes things a lot easier. You might give that a try.

**Comment by TTVert** [comment]
@stephengpowell  what exactly is the issue?  Perhaps I can help.  I do know that it will not assign ports properly unless you run a different command.
