### ISSUE TITLE
Restarting the Bridge Server Breaks the Integration

### ISSUE THREAD

**Issue by BigThunderSR** [brbeaird/SmartThings-MyQ-Edge#2]
Thanks for getting this going!

I too had to change the networking to HOST per https://github.com/brbeaird/SmartThings-MyQ-Edge/issues/1

The issue I'm seeing after getting it working is that restarting the Docker container causes the integration to break and the connectivity between ST and the bridge server is not resumed/recovered/rediscovered even after waiting multiple minutes. 

If I restart the Docker container, then I have to remove the "Garage Door Opener" and "Web Req Multi Master" items from the ST app and re-run "Scan for nearby devices".

I have re-created this sequence several times with the same outcome.

Thanks for looking in to this!

**Comment by brbeaird** [comment]
Yes, that's a known issue. Should have a fix for that soon.

**Comment by BigThunderSR** [comment]
Got it, thanks!

**Comment by brbeaird** [comment]
Fixed in #7
