### ISSUE TITLE
new ip sequence?

### ISSUE THREAD

**Issue by OneOfOneGH** [brbeaird/SmartThings-MyQ-Edge#24]
my system had been working as it should but then tonite during a winter storm the power went out for a couple of minutes. I have a generator so its not a problem but the myq-edge setup now times out when trying to connect to a network that begins with 169 and then shows a timeout after 5000 ms. needless to say this is not my subnet so why would this decide to try to connect to a new subnet when it discovered the myq opener and connected via the exact same laptop without issur prior to the power failure? I rebooted the laptop several times and even disconnected the ethernet but I get the same error everytime I restart the myqbridge app on the laptop. am I doing something wrong? for what its worth it says the sense controller is offline. I have no idea what that means

**Comment by brbeaird** [comment]
Maybe also restart your ST hub?

**Comment by OneOfOneGH** [comment]
I did. that didnt fix it. or if it did it was not an immediate fix. I had a firmware update for the router coincidentally so I decided to run it, dont know if that fixed it but the problem went away after restarting the myq-edge app again. so perhaps this is the fix for any power interruption, meaning restart the smartthings hub? very odd that nothing else was affected. thanks for your patience.

**Comment by OneOfOneGH** [comment]
it seems to be working as it should now but smartthings says the sense connector is offline. yes I am enrolled in your driver channel and yes it is installed on my hub. is there a fix for this or should I just leave things be? 
![Screenshot_20230308_092347_SmartThings](https://user-images.githubusercontent.com/47908256/223738377-03141dd6-e4d2-476d-9158-61ad92e1b3e3.jpg)

**Comment by brbeaird** [comment]
I'd say leave it be and see if SmartThings is just delayed in updating the status.
