### ISSUE TITLE
Running the bridge server with an executable

### ISSUE THREAD

**Issue by sheldondav** [brbeaird/SmartThings-MyQ-Edge#27]
Hello!

It appears that the MacOS file for the Stand-alone server is not an application than can be installed. it appears to be a text file and not a .dmg file with an application.

I did install docket with the ST-MyQ-Edge container and ran it in docker. however docker shows that it is not connected to the hub. On the  same lan....

Also when the instructions say "docker run -d --name='smartthings-myq-edge' -e 'MYQ_SERVER_PORT'='8090' -p '8090:8090/tcp' -p '1900:1900/udp' 'brbeaird/smartthings-myq-edge:latest', where are you supposed to be running this? not in terminal, for sure but maybe...

Thanks

Also long time fan for @brbeaird work from the early days of the IDE work. So a big thank you!

**Comment by brbeaird** [comment]
I don't have a Mac, so that binary is kind of a black box to me. Here is what someone suggested in the ST community forum thread:

1. run chmod 755 myQBridgeServer-macos-x64
2. Run ./myQBridgeServer-macos-x6
