### ISSUE TITLE
Alexa integration with Edge driver controlled device?

### ISSUE THREAD

**Issue by chsull** [brbeaird/SmartThings-MyQ-Edge#3]
Hi -- I previously had my garage doors integrated with the Groovy DTH device handlers and that worked fine.
I switched to the Edge driver version and the devices work fine in Smartthings but Alexa does not discover the devices.
I have the Smartthings skill enabled in Alexa and it works for other devices but the garage doors are the first Edge driver devices I've tried to integrate. Not sure if Alexa has an issue integrating these devices? Thanks for any suggestions.

**Comment by MADempsey** [comment]
Hi,  I was able to get around this by going into the SmartThings IDE and creating a simulated switch.  This device will appear in Alexa.  I changed my Alexa routine to turn on and off this new simulated device.  Then in SmartThings, I wrote 2 routines to open the new edge garage door when the simulated switch turns on.  And close the door when it turns off.  Then 2 more routines to turn the switch on if the door opens and off when it closes.  Basically trying to mirror the door’s status to the simulated switch.  So far works like a champ.

**Comment by chsull** [comment]
MADempsey -- thanks - the virtual switch work-around works great !

**Comment by MADempsey** [comment]
However this "quick fix"was short sighted.  The virtual device drivers in the IDE are also going away.  I have just completed installing the Edge virtual device drivers as found in the SmartThings Community.  Then I used the same routines as mentioned above.

**Comment by brbeaird** [comment]
The newest version of the driver should handle this and work with Alexa via switch on/off capability.
