### ISSUE TITLE
myQ API: Unable to access the OAuth authorization endpoint.  No connection

### ISSUE THREAD

**Issue by TTVert** [brbeaird/SmartThings-MyQ-Edge#31]
Anyone else seeing this?

![image](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/24374538/a6b154b2-82b6-4051-a9ca-b6f398cb5b4a)
restarted container and see this:
![image](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/24374538/f6973646-8ba7-489b-9bb3-b5f61c25a5c7)

If I open the link provided I get this.  Enter correct credentials but it doesn't like them.
![image](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/24374538/7be84099-a72c-461e-8131-d7452e50a513)

This is exactly when it started (UTC time):
![image](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/24374538/70d38acd-58cb-462d-b672-7d8b84b80028)

Dave

**Comment by TTVert** [comment]
Unfortunately I think it's safe t say we're on our own here w/ any snags.  No open issues have been addressed in some time now :(

**Comment by slynnmurphy** [comment]
@TTVert, Are you sure you are using the correct myQ email and password?  Given that the myQ website doesn't take them either, it seems like the errors are correct.

**Comment by TTVert** [comment]
Yeah nothing changed.  I eventually did get it working but I'm a bit concerned we'll be on our own w/ other issues that cannot be resolved so easily.   I'm poking around in here to familiarize myself w/ how this is functioning in the event I have to fix other random issues on my own.

**Comment by brbeaird** [comment]
Sorry, I can't do a whole lot with isolated issues. The integration has been solid for most people for months without needing any intervention. You're using basic myq credentials and not an OAuth integration like Google, right?

**Comment by TTVert** [comment]
Yes sir, my Q creds.  Confirmed to be working.  I did resolve this one some time ago but don’t recall the steps I took then.  I understand you are likely busy and are doing this out of the kindness of your heart.  I was hoping we, as a community, could work together to resolve issues when you aren’t around.  I had another post re: container binding ports and got no real response from anyone.   I was hoping I could work w/ someone else to resolve the issue to make it easier for others less tech savvy.  I did post my work around for it but anyone not savvy would be dead in the water.  But again most non savvy people wouldn’t be doing this would they?

Dave

**Comment by brbeaird** [comment]
I agree - I would love if more people were around to better troubleshoot all the possible setups, but I'm afraid the remaining population of people who are willing to go with this setup is not very large. I do get pulled in a lot of directions these days, so sometimes the most I can do is make sure it works in my particular environment (Unraid Docker) and hope others can eventually fill in the gaps for running it in other ways. That said, I use this integration every day, and it's super important to me, so I remain committed to making sure it works on that level at least.

**Comment by slynnmurphy** [comment]
I wouldn't mind helping when I can.  I'm using the Windows executable setup.  I had some issues early on where it would just randomly stop working and print messages about not being able to find things.  But since I switched internet providers (which also replaced the cable modem and router) it's been rock solid.  At this point, the only issue I have is that myQ sometimes lies about it's current state.  Even in the myQ app, it will  show it is open when it is actually closed.  I had originally  started using brbeaird's first myQ solution with the SmartThings Multipurpose sensor so I could use SmartThings to check and see what the real status of the door was when I wasn't at home.

**Comment by brbeaird** [comment]
> Even in the myQ app, it will show it is open when it is actually closed. I had originally started using brbeaird's first myQ solution with the SmartThings Multipurpose sensor so I could use SmartThings to check and see what the real status of the door was when I wasn't at home.

This is why I still have my separate physical sensor on the door. I like having 2 ways to confirm the status. Well, 3 I guess if I include the camera I could check 😄

**Comment by slynnmurphy** [comment]
I'll probably put my Multipurpose sensor back on the door.  I took it off thinking I would use it for something else, but I haven't.

**Comment by feartheclown** [comment]
I'm happy to help test this out as this issue has been driving me nuts.

Couple things I've noticed, when this occurs if you look at the MyQ-Controller in Smartthings it shows Invalid Credentials. You can always fix it by powercycling the Smartthings hub. I haven't nailed down a consistent trigger but it seems to occur when the server is dropped and then tries coming back up a couple min later but it isn't consistent. I've been doing a lot of reboots lately due to building out a new PC so I've been running into this quite a bit though it isn't consistently happening.

**Comment by brbeaird** [comment]
I made some small tweaks to version 1.0.4 that should hopefully help with the "Invalid Credentials" loop. If you still see it, let me know.

**Comment by ShadowID80** [comment]
> Yeah nothing changed. I eventually did get it working but I'm a bit concerned we'll be on our own w/ other issues that cannot be resolved so easily. I'm poking around in here to familiarize myself w/ how this is functioning in the event I have to fix other random issues on my own.

I just started getting this error... can you share what you did to resolve your issue?

**Comment by TTVert** [comment]
> > Yeah nothing changed. I eventually did get it working but I'm a bit concerned we'll be on our own w/ other issues that cannot be resolved so easily. I'm poking around in here to familiarize myself w/ how this is functioning in the event I have to fix other random issues on my own.
> 
> I just started getting this error... can you share what you did to resolve your issue?

Just happened to me again today, I actually just restarted my pc.  Tried to restart docker but that didn't fix it.

Dave

**Comment by TTVert** [comment]
> I made some small tweaks to version 1.0.4 that should hopefully help with the "Invalid Credentials" loop. If you still see it, let me know.

Sorry just saw this.  I haven't messed w/ docker in quite some time now.  What all is involved w/ updating to 1.0.4?  Create a new image w/ the new version?

**Comment by ShadowID80** [comment]
> > > Yeah nothing changed. I eventually did get it working but I'm a bit concerned we'll be on our own w/ other issues that cannot be resolved so easily. I'm poking around in here to familiarize myself w/ how this is functioning in the event I have to fix other random issues on my own.
> > 
> > 
> > I just started getting this error... can you share what you did to resolve your issue?
> 
> Just happened to me again today, I actually just restarted my pc. Tried to restart docker but that didn't fix it.
> 
> Dave

Thanks! I've tried everything including pulling the new image and remapping the ports and now the "device" from SmartThings won't connect. Docker just "listens" for a connection no matter what I try. I installed the executable version and that connected immediately. I'd prefer having Docker work but at this point I'm out of ideas.

**Comment by ShadowID80** [comment]
> 

Just use the command to pull the new image and start the container.

Pull the image down: docker pull brbeaird/smartthings-myq-edge

Start the container. The command will vary depending on platform (some do not use equal signs), but it will look something like this: docker run -d --name='smartthings-myq-edge' --network=host 'brbeaird/smartthings-myq-edge:latest'

**Comment by ShadowID80** [comment]
> 

Just pull the image using the command below and start the container.

Pull the image down: docker pull brbeaird/smartthings-myq-edge

Start the container. The command will vary depending on platform (some do not use equal signs), but it will look something like this: docker run -d --name='smartthings-myq-edge' --network=host 'brbeaird/smartthings-myq-edge:latest'

**Comment by ShadowID80** [comment]
> > I made some small tweaks to version 1.0.4 that should hopefully help with the "Invalid Credentials" loop. If you still see it, let me know.
> 
> Sorry just saw this. I haven't messed w/ docker in quite some time now. What all is involved w/ updating to 1.0.4? Create a new image w/ the new version?

Just pull the image using the command below and start the container.

Pull the image down: docker pull brbeaird/smartthings-myq-edge

Start the container. The command will vary depending on platform (some do not use equal signs), but it will look something like this: docker run -d --name='smartthings-myq-edge' --network=host 'brbeaird/smartthings-myq-edge:latest'

**Comment by TTVert** [comment]
Thank you for your continued support, this seems to have resolved that.
