### ISSUE TITLE
Getting Invalid Credentials frequently after it has been working fine

### ISSUE THREAD

**Issue by zimler** [brbeaird/SmartThings-MyQ-Edge#33]
I'm running the .exe on windows. I have recently started getting invalid credentials every other day or so. I have to go into settings, change the password to something else, not my password, save and then go back in and put in the correct password, save and then it works for a couple days more. I should say that I have a script set up that kills the server every couple hours and restarts it because I was having errors that were not resolving and was having to manually kill and restart. That has been working fine for quite a while until just recently. Any insight is appreciated.

**Comment by brbeaird** [comment]
MyQ servers have been rather unstable the last couple days. Not much we can do about that at the moment, but generally it's been coming back online eventually.

**Comment by OneOfOneGH** [comment]
same issue. since brbeaird says the have been coming back I will wait and see what happens.

**Comment by OneOfOneGH** [comment]
is there any progress on the server being up?

**Comment by zimler** [comment]
I stopped the task that restarted the server every hour, reentered my password and it's been good ever since. I'm going to close this as it is the MyQ servers and not this application causing issues.

**Comment by OneOfOneGH** [comment]
so are you saying that we just have to sit tight and wait?

**Comment by zimler** [comment]
That is what I'm saying. I stopped my auto restart of the MyQ bridge server, changed my password to something wrong, saved, gave it a moment, went back in and put in my correct password, saved and then just waited a little bit. It has been solid for several days now.

**Comment by OneOfOneGH** [comment]
it just shows 2 lines her waiting for broadcasts. nothing else.

**Comment by zimler** [comment]
Did you save a bad password and wait a few minutes? Then put in your
correct password and save again?

**Comment by OneOfOneGH** [comment]
I don’t know how to do that or where. tell me how and I will try it please. I have the myq app and it works perfectly but I assume youre talking about the server

**Comment by zimler** [comment]
Oh, I understand now. You have to do what I described regarding the
password changes in the smartthings app. In the myq hub settings.

**Comment by OneOfOneGH** [comment]
ok thanks for that. although I love tech I am not a geek.

**Comment by OneOfOneGH** [comment]
after panicking because I couldn’t find it I did the trick and it worked. thank you for your time and patience
