### ISSUE TITLE
Issue acquiring new access token

### ISSUE THREAD

**Issue by markanthony1980** [brbeaird/SmartThings-MyQ-Edge#34]
Anyone have this issue? It has been working just fine up until now and I have rebooted my hub and all and keep getting this error.
![IMG_3761](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/34868539/495ad272-fcb6-4327-bde1-094bf64e00b7)

**Comment by Hoveys** [comment]
same with me, started last night, tried the normal troubleshooting, can't get it to connect.  Smartthings keeps saying it can't find the server

**Comment by zimler** [comment]
Did you try changing your password to myq in the smart things app to
something wrong, save, and then change the password back to the correct
password and save again? I found that to sometimes help.

**Comment by OneOfOneGH** [comment]
you beat me to it. its been like this for 18 hours or so. no connection at all.

**Comment by Hoveys** [comment]
Yeah, it didn't work, but when close the program and restart it, it will
work for a few minutes and then stop again.

**Comment by OneOfOneGH** [comment]
so it doesnt work. its a fundamental issue not a password issue.

**Comment by GHN1013** [comment]
I don’t have my RaspPi monitor hooked up, but I do see my Garage Controller displaying “offline” now on SmartThings since yesterday.  Is this the same problem?

**Comment by zimler** [comment]
It seems to be cycling for me, regardless of what I do. Not sure there's
anything to do.

**Comment by GHN1013** [comment]
The Dev Brian is already aware and is working on it since yesterday.

**Comment by brbeaird** [comment]
If you're using docker, pull the latest version of the container - that should fix things for you. If you're using an executable, you'll have to wait a bit longer as I am having build issues  with those.

**Comment by markanthony1980** [comment]
> If you're using docker, pull the latest version of the container - that should fix things for you. If you're using an executable, you'll have to wait a bit longer as I am having build issues with those.

Thanks Brian! Appreciate the work you put in this.

**Comment by Hoveys** [comment]
Thank you for all your help.  I'm using the executable and willing to test anything you need!

**Comment by OneOfOneGH** [comment]
thank you brian

**Comment by GHN1013** [comment]
Thanks so much Brian!

**Comment by zimler** [comment]
Really appreciate your work on this, @brbeaird

**Comment by OneOfOneGH** [comment]
at this rate if you get the windows exe working again theres 25 bucks in it for you!

**Comment by jsalh** [comment]
> at this rate if you get the windows exe working again theres 25 bucks in it for you!

ditto - will match that.

**Comment by OneOfOneGH** [comment]
a lot easier than having him write a tutorial for windows docker. what a nightmare!

**Comment by brbeaird** [comment]
I made several attempts today but so far have not been successful. I still have some ideas to try, though, so we'll see.
The technical explanation is that the myQ library this project uses was updated to use the newer ES modules format. Normally, that's not a big deal, but the method I have used in the past to create executables (pkg) do not yet support ES modules. I've even tried using things like webpack and esbuild to distill the modules down to single cjs file, but the resulting exe file errors out in weird places. I think it's probably possible - just not going to be easy to find.

**Comment by GHN1013** [comment]
Hey Brian.  Not sure if others have reported this, but using the Docker version, I’ve had a few occurrences in last 24 hours where the MyQ Controller in ST app suddenly indicates “Invalid Credentials”.  I’ve had to re-enter the same password on the app to get it to reconnect.   Happened at least 5 times now.  Weird.

Any ideas?

**Comment by gnieboer** [comment]
Brian, thanks as always for the support!  Docker version working great, pulled and cloned, just had to change my entry point from ".js" to ".mjs" when I cloned my prior config.

**Comment by brbeaird** [comment]
Good deal - yes, the update to ES6 changes the file type to .mjs. Still hoping to figure something out for the executables but no luck yet.

**Comment by brbeaird** [comment]
Version 1.0.4 released today should resolve this. Executables found here if you're using that instead of Docker
https://github.com/brbeaird/SmartThings-MyQ-Edge/releases/tag/MyQ-Bridge-Server-v1.0.4

**Comment by Hoveys** [comment]
been running smooth for about 10 mins now.  Thank you Brian!

**Comment by jsalh** [comment]
> > at this rate if you get the windows exe working again theres 25 bucks in it for you!
> 
> ditto - will match that.

Thanks for the fix ... update works (v1.0.4).  Note I had to remove Mq-Controller from the SmartThings app, and re-add it.. and it worked after I re-entered my credentials.  (Ps .. donation made!! - thanks for all the time you put int)

**Comment by jsalh** [comment]
> > at this rate if you get the windows exe working again theres 25 bucks in it for you!
> 
> ditto - will match that.

Thanks for the fix ... update works (v1.0.4).  Note I had to remove Mq-Controller from the SmartThings app, and re-add it.. and it worked after I re-entered my credentials

**Comment by jsalh** [comment]
> > at this rate if you get the windows exe working again there's 25 bucks in it for you!
> 
> ditto - will match that.

Thanks for the fix ... update works (v1.0.4)  Note I had to remove Mq-Controller from the SmartThings app, and re-add it.. and it worked after I re-entered my credentials

**Comment by jsalh** [comment]
> > > at this rate if you get the windows exe working again there's 25 bucks in it for you!
> > 
> > 
> > ditto - will match that.
> 
> Thanks for the fix ... update works (v1.0.4) Note I had to remove Mq-Controller from the SmartThings app, and re-add it.. and it worked after I re-entered my credentials

(ps - forgot to add Donation made -- thanks for the determination in getting it to work again)

**Comment by zimler** [comment]
All is working great now, Brian. Thanks for your help and donation sent.

**Comment by OneOfOneGH** [comment]
thank you brian. donation incoming

**Comment by OneOfOneGH** [comment]
worked until this happened earlier today. then worked again until about an hour ago showing this:
![20230908_195233](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/47908256/de26b4d6-1f28-4bd4-9412-53c0d0070d5a)

**Comment by brbeaird** [comment]
Yep, new MyQ issues. Waiting to see if I need to make more changes.

**Comment by markanthony1980** [comment]
I was having the same issue yesterday but it is now working so far today.
