### ISSUE TITLE
MyQBridgeServer-win-x64 Version 1.0.3

### ISSUE THREAD

**Issue by rankl2609** [brbeaird/SmartThings-MyQ-Edge#36]
This used to work for me.  

However, I'm getting something in my MyQBridgeServer-win-x64 log that says new version 1.0.3 is available, but I don't see where I can update to this latest version.  

Also, I'm getting:  
myQ API: https://partner-identity.myq-cloud.com/connect/authorize?client_id=IOS_CGI_MYQ&code_challenge=zDSjhm4eujX11dCDjvJhDcGP28zm2cc6JbpoW-4V2Jw&code_challenge_method=S256&redirect_uri=com.myqops%3A%2F%2Fios&response_type=code&scope=MyQ_Residential+offline_access Error: 403 Forbidden
myQ API: Unable to access the OAuth authorization endpoint.
9/6/2023, 7:37:40 PM | Refresh failed

I have been having problems lately where the MyQ Controller shows as Offline in SmartThings.  Are these related?

**Comment by rankl2609** [comment]
I see that the MyQ-Connector driver was updated 2023-09-02,  When I check the myQStatus in SmartThings, it shows Invalid credentials.  I have not changed the MyQ app login and password and I know that the credentials are correct because the MyQ app works fine.  I just can't get this to work from SmartThings anymore.  Please help Brian!

**Comment by zimler** [comment]
Brian's working on a new version.

**Comment by feartheclown** [comment]
i don't know if you've tried it but i ended up switching to the Docker version finally. Turned out the issue I had originally with it working was getting the ports to bind. There is another thread in here about it where the poster put in the code needed to resolve that. Just tossing that out there in case like me you had tried and had issues with it and ended up using the EXE instead.

**Comment by rankl2609** [comment]
Thanks feartheclown.  When I first installed this in SmartThings, I tried using the Docker method instead of the EXE...  but I didn't know what I was doing...  and when I tried the EXE, it automatically configured the necessary firewall settings, etc.  So I've been using the EXE since I started using the Edge connector and haven't had a problem until recently.

**Comment by brbeaird** [comment]
See version 1.0.4 released today
https://github.com/brbeaird/SmartThings-MyQ-Edge/releases/tag/MyQ-Bridge-Server-v1.0.4

**Comment by zimler** [comment]
In the 1.0.4 windows executable it says there's a new version available, but I downloaded the latest version. Did I do something wrong?

**Comment by brbeaird** [comment]
Bah. Must have run the package before bumping the version. I just refreshed the executables once more. If you use the one there now, you should see it running as 1.0.4.

**Comment by rankl2609** [comment]
I downloaded the version 1.0.4 and it shows that on the first line of the log.  However, I am getting:
9/7/2023, 10:50:49 AM | SmartThings hub acknowledged auto-discovery response (status: 200). If this message repeats, it means the hub cannot connect to this server's URL due to firewall or network issues.
and I am getting it to repeat.  

I confirmed that both my SmartHub, PC running the 1.0.4 version, and my smartphone are all on the same wifi network.  I also deleted and re-installed the MyQ-Controller in SmartThings and put in my MyQ login credentials, and I still get the repeating message.

Did anything have to change with the firewall settings due to the new version 1.0.4?  

Thanks Brian!

**Comment by brbeaird** [comment]
No, the code changes should not have affected network connectivity. The first thing to try is to find the "myqserveraddress" URL that shows in the MyQ-Connector device in the ST mobile app and then try to hit that URL in the browser of some other machine on the network (your phone maybe). If you get no response, something is preventing it from being exposed to the network. Hard to say what that is, though.

**Comment by rankl2609** [comment]
I also confirmed that I have 2 Inbound Rules in my firewall settings for myqbridgeserver-win-x64.exe...  1 for Protocol Type TCP with Protocol number 6, and the other for Protocol Type UDP with Protocol number 17.  I also confirmed that I have Environmental variable MYQ_SERVER_PORT with value 8090.

I tried both drivers MyQ Connector and MyQ ConnectorBETA for the MyQ Controller.  The BETA version doesn't seem to work at all.  The non-BETA driver is the one causing the repeating problem in version 1.0.4.

**Comment by rankl2609** [comment]
I don't have any ports set manually.  I relied on the leaving the Server IP and Server Port blank in the settings for MyQ-Controller.  The myqserveraddress is http://192.168.2.12:8090 and I can't get to that from either my laptop running version 1.0.4 nor my smartphone.  The myQStatus shows Error: MyQ Bridge Offline:  http://192.168.2.12:8090.

Thanks

**Comment by zimler** [comment]
I received that message only once when I started the executable and
everything works in the smartthings app fine.

**Comment by rankl2609** [comment]
I rebooted my laptop running version 1.0.4, and now it appears that everything is working!!!

**Comment by jasonkaruza** [comment]
Many thanks @brbeaird !!! You rock ❤️
