### ISSUE TITLE
New to this having trouble running the bridge server

### ISSUE THREAD

**Issue by rschulingkamp** [brbeaird/SmartThings-MyQ-Edge#39]
Hello,
Can any one help me at all?  I'm running this on a Raspberry Pi 4.  I believe I got Docker installed and running correctly.  But when I pull the image down or start the container I get errors.
Obviously I have a lot to learn, but I'm frustrated.
See below.

XXX@raspberrypi:~$ docker pull brbeaird/smartthings-myq-edge
Using default tag: latest
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=brbeaird%2Fsmartthings-myq-edge&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
XXX@raspberrypi:~$ docker run -d --name='smartthings-myq-edge' --network=host 'brbeaird/smartthings-myq-edge:latest'
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=smartthings-myq-edge": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
XXX@raspberrypi:~$ docker run -d --security-opt=seccomp=unconfined --restart='always' --name='smartthings-myq-edge' --network=host 'brbeaird/smartthings-myq-edge:latest'
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create?name=smartthings-myq-edge": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

**Comment by brbeaird** [comment]
You may need to run that with sudo to gain admin permissions.

**Comment by rschulingkamp** [comment]
Yes, that was it, the problem.Any way to make the app update if the server, Raspberry Pi, gets a IP address change?  Or should I just make the Pi have a static IP?Thanks Bob 
-------- Original message --------From: Brian Beaird ***@***.***> Date: 9/30/23  12:47 PM  (GMT-05:00) To: brbeaird/SmartThings-MyQ-Edge ***@***.***> Cc: rschulingkamp ***@***.***>, Author ***@***.***> Subject: Re: [brbeaird/SmartThings-MyQ-Edge] New to this having trouble running the bridge server (Issue #39) 
You may need to run that with sudo to gain admin permissions.

**Comment by rschulingkamp** [comment]
Ok, for 3 weeks it ran without any issue, then today I noticed it wasn't working.  Suddenly, w/o changing anything, the MyQ-Controller is reporting in status "Error: Bridge server failed to login to MyQ: Unauthorized".  
I stopped and removed and reinstalled the Docker container, I uninstalled and reinstalled the Edger driver and I deleted the app controller device and then reinstalled it.  double checked the MyQ login Email and password.
I'm at a loss......
Anyone can direct me???  Please...

**Comment by brbeaird** [comment]
I am sorry to say this integration is officially dead, at least for the time being. The API changes by MyQ are dramatic and are not possible to overcome at this point. I suggest looking at alternatives like Meross. I also have a Ratgdo device on order - once I get my hands on it, I may see if I can get that integrated with SmartThings as a replacement.
