### ISSUE TITLE
Error:Bridge server failed to login to MyQ: Unauthorized

### ISSUE THREAD

**Issue by seseyffe** [brbeaird/SmartThings-MyQ-Edge#41]
Hi Brian,

I've had the MyQ integration installed for at least  months now.  Recently, (like the past 2 weeks) i see notifications that my garage door is offline, then online, then offline, like 10+ times a day.  When i go to the MyQ Controller in the ST app, i see the following error.

what is going on, and more importantly, how can i fix this?

![IMG_4118](https://github.com/brbeaird/SmartThings-MyQ-Edge/assets/48224654/720a5115-3ef4-426c-b97f-24fdfee92417)

Thanks in advance!
Steve

**Comment by John43528** [comment]
I was having the same issue. I got the latest .exe and it is working again.

**Comment by seseyffe** [comment]
I am using the docker image, is there a way to update the docker image?  Has there been a recent change to the image?

Thanks,
Steve
________________________________

**Comment by seseyffe** [comment]
I removed the existing image, downloaded lastest and restarted docker, seems to be running fine now, thanks!

Thanks,
Steve
________________________________

**Comment by seseyffe** [comment]
Thanks Brian.   I meant to close it but am on the road away from the laptop.  Appreciate the help!

Thanks,
Steve
________________________________
