### ISSUE TITLE
Problem with latest executable version myQBridgeServer-win-x64 version 1.0.4?

### ISSUE THREAD

**Issue by rankl2609** [brbeaird/SmartThings-MyQ-Edge#45]
My executable just started giving me problems with repeating error 429.  See log below:
10/11/2023, 7:56:24 AM | SmartThings MyQ Bridge server: Version: 1.0.4
10/11/2023, 7:56:24 AM | HTTP server listening on port 8090
10/11/2023, 7:56:24 AM | Auto-discovery module listening for SmartThings hub requests
10/11/2023, 7:56:26 AM | Got new username/password from hub. Initializing connection to MyQ.
myQ API error: API call returned error: 429.
10/11/2023, 7:56:26 AM | Refresh failed
10/11/2023, 7:56:26 AM | Refresh error: refresh failed
10/11/2023, 7:56:26 AM | Got new username/password from hub. Initializing connection to MyQ.
myQ API error: API call returned error: 429.

This just started happening.  I've rebooted and problem persists.

**Comment by John43528** [comment]
same issue here but i had the previous win exe with the same issue.  maybe something changes on MyQ API.

**Comment by rankl2609** [comment]
I tried using the Windows Docker Desktop option, and it doesn't find the MyQ-Controller device in SmartThings either....  so could be an issue with the MyQ API as neither the Docker or Windows executable seems to be working now.

**Comment by brbeaird** [comment]
I would try shutting it off for an hour or so and then trying again, maybe set your polling interval higher to like 30 seconds.

**Comment by rankl2609** [comment]
Tried your suggestion, and that didn't help.  On the MyQ-Controller myQStatus shows "Error: Bridge server unable to refresh MyQ devices: refresh failed"

This WAS working fine for me until recently.

**Comment by tonyr1512** [comment]
The issue I think might be the API everything isn't working that isn't the app itself. brbeaird, did the api change or is this an outage with the API itself can you confirm?

**Comment by rankl2609** [comment]
If it IS the API, that is just another confirmation that my decision to buy the Tailwind iQ3 Smart Automatic Garage Controller PRO was a good one.  I'm sick of Chamberlain's crap that they put out.  The Tailwind controller works directly with Android Auto and also has seamless integration with Google Home, Alexa, and Siri.  Can't wait for it to arrive and dump the MyQ controller!!!

**Comment by brbeaird** [comment]
> did the api change or is this an outage with the API itself can you confirm?

Have not been able to confirm yet. My setup has been working without issue, but I can tell from my logs that I am pointing to MyQ-West, so that may be part of it. I'm running a slightly newer test version of the Docker image I wrote that dynamically fails over between east/west if it runs into problems.

**Comment by SGKrueger** [comment]
My setup was working without issue, until I installed and restarted after the MS Patch Tuesday releases. Now I'm getting the same error as rankl2609.

**Comment by rtorchia** [comment]
Same with me
```
myQ API error: API call returned error: 429.
```
Seems like it's an api issue as it's happening with all implementations to access myq, except for there official app.

**Comment by trippcat** [comment]
I'm also having authentication issues... i backed my polling to 60 seconds, so I'm no longer getting the 429 errors, but clearly, authorization is not working on the API.  I'm running the latest docker image and this was working fine prior to my PC doing a windows update and restarting in the last day.  Here is what I'm seeing in the logs:
2023-10-12 08:56:13 10/12/2023, 12:56:13 PM | MyQ login failed
2023-10-12 09:02:12 10/12/2023, 1:02:12 PM | Initializing connection to MyQ-west.
2023-10-12 09:02:13 myQ API error: Invalid myQ credentials given: Check your username and password. If they are correct, the myQ API may be experiencing temporary issues.
2023-10-12 09:02:13 10/12/2023, 1:02:13 PM | MyQ login failed

**Comment by brbeaird** [comment]
It definitely seems to be an API issue, and it's related to new auth sessions. If you already have a working session, it's probably still fine. But if you restarted, it is likely to not be able to connect at all. Other integration projects are dealing with this, too.

The author of the myq library this project uses has a policy to ignore API errors like this unless they go on for more than a day or two. In the past, this has proven wise because the majority of time, these things silently clear themselves up without any change needed. If he does end up making a change, I will get these updated here as needed.

I do also follow the other projects pretty closely, and it's worth noting the arraylabs/pymyq project is reporting a possible fix for this. I am hoping to find some time today to look into that and see if I could implement it in the library we use.

**Comment by rankl2609** [comment]
I updated to version 1.0.5 of the myQBridgeServer-win-x64.exe and that took care of the 429 error, but now I'm getting:
10/13/2023, 11:06:35 AM | SmartThings MyQ Bridge server: Version: 1.0.5
10/13/2023, 11:06:35 AM | HTTP server listening on port 8090
10/13/2023, 11:06:35 AM | Auto-discovery module listening for SmartThings hub requests
10/13/2023, 11:06:36 AM | Got new username/password from hub.
myQ API error: Invalid myQ credentials given. Check your login and password.
10/13/2023, 11:06:36 AM | MyQ login failed

I verified that my MyQ login credentials are correct, so something is still broke.  Thanks,

**Comment by brbeaird** [comment]
Issues should be fixed with latest release https://github.com/brbeaird/SmartThings-MyQ-Edge/releases/tag/MyQ-Bridge-Server-v1.0.5

It may not work immediately. I had to keep mine shut off for several hours, then brought it back online, and it's working again.

**Comment by John43528** [comment]
this appears to have resolved for me now.  thank you!

**Comment by zimler** [comment]
After leaving 1.0.5 off for a while, when I started it everything is
working, however it says there's a version 1.0.6. Am i missing something?

**Comment by rankl2609** [comment]
Same for me.  After leaving it off for approx. 2 hours, version 1.0.5 seems to be working, however I also am getting:
10/13/2023, 1:08:37 PM | SmartThings MyQ Bridge server: Version: 1.0.5
10/13/2023, 1:08:37 PM | HTTP server listening on port 8090
10/13/2023, 1:08:37 PM | Auto-discovery module listening for SmartThings hub requests
10/13/2023, 1:08:38 PM | Newer server version is available (1.0.5 => 1.0.6)
10/13/2023, 1:08:40 PM | Got new username/password from hub.
myQ API: Successfully connected to the myQ API.
myQ API: Discovered device family gateway: Garage Door Old MyQ (serial number: GW030005B37F).
myQ API: Discovered device family garagedoor: Garage Door With Old MyQ [Liftmaster WiFi GDO DC w/Battery Backup] (serial number: CG08430B66FE, gateway: GW030005B37F).

When I check, I don't see a version 1.0.6 available.

**Comment by rankl2609** [comment]
I spoke too soon...  No longer getting error messages in the version 1.0.5 log, however, when I try to use the MyQ-Controller in SmartThings to close my open garage door, the MyQStatus goes from "Connected" to "close command failed" and then I get a popup on my phone saying "A network or server error occurred. Try again later." and garage door remains open.

Here's my latest log:
10/13/2023, 1:20:20 PM | SmartThings MyQ Bridge server: Version: 1.0.5
10/13/2023, 1:20:20 PM | HTTP server listening on port 8090
10/13/2023, 1:20:20 PM | Auto-discovery module listening for SmartThings hub requests
10/13/2023, 1:20:20 PM | Newer server version is available (1.0.5 => 1.0.6)
10/13/2023, 1:20:26 PM | Detected auto-discovery request from SmartThings Hub (http://192.168.2.21:41093/ping). Replying with bridge server URL.
10/13/2023, 1:20:26 PM | SmartThings hub acknowledged auto-discovery response. If this message repeats, it means the hub received the bridge server IP/Port but cannot connect to it due to firewall or network issues.
10/13/2023, 1:20:26 PM | Got new username/password from hub.
myQ API: Successfully connected to the myQ API.
myQ API: Discovered device family gateway: Garage Door Old MyQ (serial number: GW030005B37F).
myQ API: Discovered device family garagedoor: Garage Door With Old MyQ [Liftmaster WiFi GDO DC w/Battery Backup] (serial number: CG08430B66FE, gateway: GW030005B37F).
10/13/2023, 1:20:56 PM | Setting Garage Door With Old MyQ to close

Will the version 1.0.6 fix this when it's available?

**Comment by andersa99** [comment]
I'm still getting the new version notice. I'm going to stop trying for a bit and see if it resolves.

**Comment by brbeaird** [comment]
I'm working on another fix, which will be 1.0.6. Hold tight.

**Comment by andersa99** [comment]
Will do, no pressure. I was excited to get the last version which worked for a while after a long period of no success. Appreciate all you do. Where can I donate a token of my appreciation to your work?

Arnold Anderson

**Comment by brbeaird** [comment]
Alright, 1.0.6 should do it https://github.com/brbeaird/SmartThings-MyQ-Edge/releases/tag/MyQ-Bridge-Server-v1.0.6

Cups of coffee are always appreciated! https://github.com/brbeaird/SmartThings-MyQ-Edge#special-thanks

**Comment by rankl2609** [comment]
Version 1.0.6 works for me!  Door opens and closes and no errors.  Here's the 1.0.6 log:
10/13/2023, 3:12:40 PM | SmartThings MyQ Bridge server: Version: 1.0.6
10/13/2023, 3:12:40 PM | HTTP server listening on port 8090
10/13/2023, 3:12:40 PM | Auto-discovery module listening for SmartThings hub requests
10/13/2023, 3:12:45 PM | Got new username/password from hub.
myQ API: Successfully connected to the myQ API.
myQ API: Discovered device family gateway: Garage Door Old MyQ (serial number: GW030005B37F).
myQ API: Discovered device family garagedoor: Garage Door With Old MyQ [Liftmaster WiFi GDO DC w/Battery Backup] (serial number: CG08430B66FE, gateway: GW030005B37F).
10/13/2023, 3:13:07 PM | Sending close command for Garage Door With Old MyQ
10/13/2023, 3:13:35 PM | Updating Garage Door With Old MyQ state from open to closed
10/13/2023, 3:14:29 PM | Sending open command for Garage Door With Old MyQ
10/13/2023, 3:14:46 PM | Updating Garage Door With Old MyQ state from closed to open

Thanks Brian!!!

**Comment by brbeaird** [comment]
Good deal. You can see more detailed state logging in there now, too, which I'm liking.
