### ISSUE TITLE
403 Forbidden error when trying to open or close garage 

### ISSUE THREAD

**Issue by compmas2** [brbeaird/SmartThings-MyQ-Edge#5]
I have had your MyQ edge proxy software running for several days in a docker container with no issues until now.  I have changed nothing about my setup.  Either this morning or last night, I started getting the following everytime I try to open or close my garage:

`myQ API: https://account-devices-gdo.myq-cloud.com/api/v5.2/Accounts/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/door_openers/XXXXXXXXXXXX/close Error: 403 Forbidden
myQ API: Unable to send the command to myQ servers. Acquiring a new access token.
myQ API: Successfully connected to the myQ API.`

I replaced the parts of the web address that are specific to my account with multiple x or X.  At this point this edge driver proxy is not working at all.

Please let me know if you need more details to debug this issue.

**Comment by brbeaird** [comment]
Occasional myqAPI errors are normal - the myQ platform is not the most
reliable. It normally self-resolves over time.

**Comment by compmas2** [comment]
It appears it has resolved itself on its own as you said.  Thanks for the information about the MyQ platform API stability.  Sorry for the noise.

**Comment by brbeaird** [comment]
No worries. I'll add mention of that to the docs when I get some time.
