### ISSUE TITLE
Password Field in MyQ Controller Device Needs to be Masked

### ISSUE THREAD

**Issue by BigThunderSR** [brbeaird/SmartThings-MyQ-Edge#8]
Could you please mask the password field in the MyQ Controller Device within the SmartThings app?

Thanks!

**Comment by brbeaird** [comment]
I wish I could, but that's a SmartThings limitation for now. I use the "password" type in the profile, but the app fails to hide it.

https://community.smartthings.com/t/auth-token-for-edge/251043

**Comment by BigThunderSR** [comment]
That's unfortunate. ☹️

**Comment by brbeaird** [comment]
The issue has been logged by ST devs, so it should get fixed eventually.
