### ISSUE TITLE
Feature Request - Not an Issue

### ISSUE THREAD

**Issue by ViperTK** [brbeaird/SmartThings-MyQ-Edge#9]
Brian, didn't know how to request a feature so, creating this issue here.
Whenever you update the driver next time and if it's not too much work , is there a way to add displaying the server IP and maybe port that the MyQConnector driver is connecting to.

Use Case:
I've the bridge server running on my Pine64 SBC on Docker and natively as a service on Windows as well. I left the Windows instance just as a backup and to see what happens and it kinda saved me when my docker machine accidentally went down. I don't configure the IP & Port in the driver, and rely on your ssdp inclusion. the driver instantly connected to the Windows instance when this happened and I didn't loose access to the doors.
So, I would like to keep this structure, but would like an easy way to know which server the driver is being served from. Right now, CLI shows this during the 10 second refresh log.

PS: your next coffee is on me. you should see a small token of appreciation for your work on Paypal.

**Comment by brbeaird** [comment]
Thanks! Yes, that's a really good idea. I'll find a place to show that.

**Comment by brbeaird** [comment]
Newest driver version now shows server IP/port of the bridge server.

**Comment by ViperTK** [comment]
Thanks. (Y)
